#ifndef TASK_H
#define TASK_H

#include <string>
#include <chrono>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

/**
 * Represents a computational task generated by IoT device data
 * Tasks are allocated to edge nodes for processing
 */
class Task {
public:
    enum class TaskPriority {
        LOW = 0,
        MEDIUM = 1,
        HIGH = 2,
        CRITICAL = 3
    };

    enum class TaskStatus {
        CREATED,
        QUEUED,
        RUNNING,
        COMPLETED,
        FAILED,
        REALLOCATED
    };

    struct TaskRequirements {
        double cpu_percent;          // CPU required (0-100%)
        double ram_mb;               // RAM required (in MB)
        double bandwidth_mbps;       // Bandwidth required (in Mbps)
        int64_t deadline_ms;         // Deadline (in milliseconds)
        TaskPriority priority;
    };

    // Constructor
    Task(
        const std::string& task_id,
        const std::string& device_id,
        const std::string& sensor_type,
        const TaskRequirements& requirements,
        const json& sensor_data
    );

    // Getters
    std::string getTaskId() const { return task_id_; }
    std::string getDeviceId() const { return device_id_; }
    std::string getSensorType() const { return sensor_type_; }
    TaskRequirements getRequirements() const { return requirements_; }
    json getSensorData() const { return sensor_data_; }
    TaskStatus getStatus() const { return status_; }
    std::string getAssignedEdgeId() const { return assigned_edge_id_; }
    
    // Timing
    std::chrono::system_clock::time_point getCreationTime() const { return creation_time_; }
    std::chrono::system_clock::time_point getCompletionTime() const { return completion_time_; }
    int64_t getElapsedTimeMs() const;
    int64_t getRemainingTimeMs() const;
    bool isDeadlineExceeded() const;

    // Setters
    void setStatus(TaskStatus status) { status_ = status; }
    void setAssignedEdgeId(const std::string& edge_id) { assigned_edge_id_ = edge_id; }
    void setCompletionTime(std::chrono::system_clock::time_point time) { completion_time_ = time; }

    // JSON serialization
    json toJson() const;
    static Task fromJson(const json& j);

private:
    std::string task_id_;
    std::string device_id_;
    std::string sensor_type_;
    TaskRequirements requirements_;
    json sensor_data_;
    TaskStatus status_;
    std::string assigned_edge_id_;
    std::chrono::system_clock::time_point creation_time_;
    std::chrono::system_clock::time_point completion_time_;
};

#endif // TASK_H
